package com.dpstudio.dev.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.IShardingable;
import net.ymate.platform.persistence.annotation.*;
import net.ymate.platform.persistence.jdbc.IConnectionHolder;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * MimiprogramUser generated By EntityGenerator on 2020/04/02 下午 18:09:47
 *
 * @author YMP
 * @version 1.0
 */
@Entity(MimiprogramUser.TABLE_NAME)
public class MimiprogramUser extends BaseEntity<MimiprogramUser, String> {

	private static final long serialVersionUID = 1L;

	@Id
	@Property(name = FIELDS.ID, nullable = false, length = 32)
	@Comment("")
    @PropertyState(propertyName = FIELDS.ID)
	private String id;
	
	@Property(name = FIELDS.OPEN_ID, nullable = false, length = 256)
	@Comment("")
    @PropertyState(propertyName = FIELDS.OPEN_ID)
	private String openId;
	
	@Property(name = FIELDS.UNION_ID, length = 32)
	@Comment("")
    @PropertyState(propertyName = FIELDS.UNION_ID)
	private String unionId;
	
	@Property(name = FIELDS.NICK_NAME, length = 32)
	@Comment("昵称")
    @PropertyState(propertyName = FIELDS.NICK_NAME)
	private String nickName;
	
	@Property(name = FIELDS.PHOTO, length = 32)
	@Comment("手机号")
    @PropertyState(propertyName = FIELDS.PHOTO)
	private String photo;
	
	@Property(name = FIELDS.GENDER, unsigned = true, length = 1)
	@Default("0")
	@Comment("性别")
    @PropertyState(propertyName = FIELDS.GENDER)
	private Integer gender;
	
	@Property(name = FIELDS.AVATAR_URL, length = 255)
	@Comment("头像")
    @PropertyState(propertyName = FIELDS.AVATAR_URL)
	private String avatarUrl;
	
	@Property(name = FIELDS.COUNTRY, length = 32)
	@Comment("国家")
    @PropertyState(propertyName = FIELDS.COUNTRY)
	private String country;
	
	@Property(name = FIELDS.PROVINCE, length = 32)
	@Comment("省份")
    @PropertyState(propertyName = FIELDS.PROVINCE)
	private String province;
	
	@Property(name = FIELDS.CITY, length = 32)
	@Comment("城市")
    @PropertyState(propertyName = FIELDS.CITY)
	private String city;
	
	@Property(name = FIELDS.CREATE_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("")
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
	private Long createTime;
	
	@Property(name = FIELDS.LAST_MODIFY_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("最后修改时间")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_TIME)
	private Long lastModifyTime;

	/**
	 * 构造器
	 */
	public MimiprogramUser() {
	}

    /**
     * 构造器
     *	@param id
     *	@param openId
     *	@param createTime
     *	@param lastModifyTime
     */
    public MimiprogramUser(String id, String openId, Long createTime, Long lastModifyTime) {
        this.id = id;
        this.openId = openId;
        this.createTime = createTime;
        this.lastModifyTime = lastModifyTime;
    }

	/**
	 * 构造器
	 *	@param id
	 *	@param openId
	 *	@param unionId
	 *	@param nickName
	 *	@param photo
	 *	@param gender
	 *	@param avatarUrl
	 *	@param country
	 *	@param province
	 *	@param city
	 *	@param createTime
	 *	@param lastModifyTime
	 */
	public MimiprogramUser(String id, String openId, String unionId, String nickName, String photo, Integer gender, String avatarUrl, String country, String province, String city, Long createTime, Long lastModifyTime) {
		this.id = id;
		this.openId = openId;
		this.unionId = unionId;
		this.nickName = nickName;
		this.photo = photo;
		this.gender = gender;
		this.avatarUrl = avatarUrl;
		this.country = country;
		this.province = province;
		this.city = city;
		this.createTime = createTime;
		this.lastModifyTime = lastModifyTime;
	}

    @Override
	public String getId() {
		return id;
	}

    @Override
	public void setId(String id) {
		this.id = id;
	}


	/**
	 * @return the openId
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * @param openId the openId to set
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * @return the unionId
	 */
	public String getUnionId() {
		return unionId;
	}

	/**
	 * @param unionId the unionId to set
	 */
	public void setUnionId(String unionId) {
		this.unionId = unionId;
	}

	/**
	 * @return the nickName
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * @param nickName the nickName to set
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * @return the photo
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * @param photo the photo to set
	 */
	public void setPhoto(String photo) {
		this.photo = photo;
	}

	/**
	 * @return the gender
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * @param gender the gender to set
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * @return the avatarUrl
	 */
	public String getAvatarUrl() {
		return avatarUrl;
	}

	/**
	 * @param avatarUrl the avatarUrl to set
	 */
	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	/**
	 * @return the country
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * @param country the country to set
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * @return the province
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * @param province the province to set
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * @return the city
	 */
	public String getCity() {
		return city;
	}

	/**
	 * @param city the city to set
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @return the createTime
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the lastModifyTime
	 */
	public Long getLastModifyTime() {
		return lastModifyTime;
	}

	/**
	 * @param lastModifyTime the lastModifyTime to set
	 */
	public void setLastModifyTime(Long lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}


	//
	// Chain
	//

	public static MimiprogramUserBuilder builder() {
		return new MimiprogramUserBuilder();
	}

	public MimiprogramUserBuilder bind() {
    	return new MimiprogramUserBuilder(this);
    }

	public static class MimiprogramUserBuilder {

		private MimiprogramUser _model;

		public MimiprogramUserBuilder() {
			_model = new MimiprogramUser();
		}

		public MimiprogramUserBuilder(MimiprogramUser model) {
			_model = model;
		}

		public MimiprogramUser build() {
			return _model;
		}


		public IConnectionHolder connectionHolder() {
			return _model.getConnectionHolder();
		}

		public MimiprogramUserBuilder connectionHolder(IConnectionHolder connectionHolder) {
			_model.setConnectionHolder(connectionHolder);
			return this;
		}

		public String dataSourceName() {
			return _model.getDataSourceName();
		}

		public MimiprogramUserBuilder dataSourceName(String dsName) {
			_model.setDataSourceName(dsName);
			return this;
		}

		public IShardingable shardingable() {
			return _model.getShardingable();
		}

		public MimiprogramUserBuilder shardingable(IShardingable shardingable) {
    		_model.setShardingable(shardingable);
    		return this;
    	}

		public String id() {
			return _model.getId();
		}

		public MimiprogramUserBuilder id(String id) {
			_model.setId(id);
			return this;
		}

		public String openId() {
			return _model.getOpenId();
		}

		public MimiprogramUserBuilder openId(String openId) {
			_model.setOpenId(openId);
			return this;
		}

		public String unionId() {
			return _model.getUnionId();
		}

		public MimiprogramUserBuilder unionId(String unionId) {
			_model.setUnionId(unionId);
			return this;
		}

		public String nickName() {
			return _model.getNickName();
		}

		public MimiprogramUserBuilder nickName(String nickName) {
			_model.setNickName(nickName);
			return this;
		}

		public String photo() {
			return _model.getPhoto();
		}

		public MimiprogramUserBuilder photo(String photo) {
			_model.setPhoto(photo);
			return this;
		}

		public Integer gender() {
			return _model.getGender();
		}

		public MimiprogramUserBuilder gender(Integer gender) {
			_model.setGender(gender);
			return this;
		}

		public String avatarUrl() {
			return _model.getAvatarUrl();
		}

		public MimiprogramUserBuilder avatarUrl(String avatarUrl) {
			_model.setAvatarUrl(avatarUrl);
			return this;
		}

		public String country() {
			return _model.getCountry();
		}

		public MimiprogramUserBuilder country(String country) {
			_model.setCountry(country);
			return this;
		}

		public String province() {
			return _model.getProvince();
		}

		public MimiprogramUserBuilder province(String province) {
			_model.setProvince(province);
			return this;
		}

		public String city() {
			return _model.getCity();
		}

		public MimiprogramUserBuilder city(String city) {
			_model.setCity(city);
			return this;
		}

		public Long createTime() {
			return _model.getCreateTime();
		}

		public MimiprogramUserBuilder createTime(Long createTime) {
			_model.setCreateTime(createTime);
			return this;
		}

		public Long lastModifyTime() {
			return _model.getLastModifyTime();
		}

		public MimiprogramUserBuilder lastModifyTime(Long lastModifyTime) {
			_model.setLastModifyTime(lastModifyTime);
			return this;
		}

	}

	/**
	 * MimiprogramUser 字段常量表
	 */
	public class FIELDS {
		public static final String ID = "id";
		public static final String OPEN_ID = "open_id";
		public static final String UNION_ID = "union_id";
		public static final String NICK_NAME = "nick_name";
		public static final String PHOTO = "photo";
		public static final String GENDER = "gender";
		public static final String AVATAR_URL = "avatar_url";
		public static final String COUNTRY = "country";
		public static final String PROVINCE = "province";
		public static final String CITY = "city";
		public static final String CREATE_TIME = "create_time";
		public static final String LAST_MODIFY_TIME = "last_modify_time";
	}

	public static final String TABLE_NAME = "mimiprogram_user";

}
