/*
 * Copyright 2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dpstudio.dev.security.annotation;

import com.dpstudio.dev.security.IAuthenticator;

import java.lang.annotation.*;

/**
 * SecurityConf generated By ModuleMojo on 2020/06/30 17:49
 *
 * @author YMP (https://www.ymate.net/)
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface SecurityConf {

    /**
     * @return 模块是否已启用, 默认值: true
     */
    boolean enabled() default true;

    /**
     * @return 权限包名
     */
    String packageName() default "";

    /**
     * @return 菜单文件位置
     */
    String menuFilePath() default "${root}/menu/menu.xml";

    /**
     * @return 授权实现类
     */
    Class<? extends IAuthenticator> authenticatorClass() default IAuthenticator.DefaultAuthenticator.class;
}
