/*
 * Copyright 2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dpstudio.dev.security.impl;

import com.dpstudio.dev.security.IAuthenticator;
import com.dpstudio.dev.security.annotation.SecurityConf;
import com.dpstudio.dev.security.ISecurity;
import com.dpstudio.dev.security.ISecurityConfig;
import net.ymate.platform.commons.util.ClassUtils;
import net.ymate.platform.core.configuration.IConfigReader;
import net.ymate.platform.core.module.IModuleConfigurer;
import org.apache.commons.lang3.StringUtils;

/**
 * DefaultSecurityConfig generated By ModuleMojo on 2020/06/30 17:49
 *
 * @author YMP (https://www.ymate.net/)
 */
public final class DefaultSecurityConfig implements ISecurityConfig {

    private boolean enabled = true;
    private String packageName;
    private String menuFilePath;
    private IAuthenticator authenticatorClass;


    private boolean initialized;

    public static DefaultSecurityConfig defaultConfig() {
        return builder().build();
    }

    public static DefaultSecurityConfig create(IModuleConfigurer moduleConfigurer) {
        return new DefaultSecurityConfig(null, moduleConfigurer);
    }

    public static DefaultSecurityConfig create(Class<?> mainClass, IModuleConfigurer moduleConfigurer) {
        return new DefaultSecurityConfig(mainClass, moduleConfigurer);
    }

    public static Builder builder() {
        return new Builder();
    }

    private DefaultSecurityConfig() {
    }

    private DefaultSecurityConfig(Class<?> mainClass, IModuleConfigurer moduleConfigurer) {
        IConfigReader configReader = moduleConfigurer.getConfigReader();
        SecurityConf confAnn = mainClass == null ? null : mainClass.getAnnotation(SecurityConf.class);
        enabled = configReader.getBoolean(ENABLED, confAnn == null || confAnn.enabled());
        packageName = configReader.getString(PACKAGE_NAME, confAnn != null ? confAnn.packageName() : "");
        menuFilePath = configReader.getString(MENU_FILE_PATH, confAnn != null ? confAnn.menuFilePath() : "${root}/menu/menu.xml");
        String authenticatorClassName = configReader.getString(AUTHENTICATOR_CLASS, confAnn != null ? confAnn.authenticatorClass().getName() : null);
        authenticatorClass = ClassUtils.impl(authenticatorClassName, IAuthenticator.class, this.getClass());
    }

    @Override
    public void initialize(ISecurity owner) {
        if (!initialized) {
            if (enabled) {
                packageName = StringUtils.trimToEmpty(packageName);
                menuFilePath = StringUtils.trimToEmpty(menuFilePath);
                if (authenticatorClass == null) {
                    authenticatorClass = new IAuthenticator.DefaultAuthenticator();
                }
            }
            initialized = true;
        }
    }

    @Override
    public boolean isInitialized() {
        return initialized;
    }

    @Override
    public boolean isEnabled() {
        return enabled;
    }

    @Override
    public String packageName() {
        return packageName;
    }

    @Override
    public String menuFilePath() {
        return menuFilePath;
    }

    @Override
    public IAuthenticator authenticatorClass() {
        return authenticatorClass;
    }

    public void setEnabled(boolean enabled) {
        if (!initialized) {
            this.enabled = enabled;
        }
    }

    public void setPackageName(String packageName) {
        if (!initialized) {
            this.packageName = packageName;
        }
    }

    public void setMenuFilePath(String menuFilePath) {
        if (!initialized) {
            this.menuFilePath = menuFilePath;
        }
    }

    public void setAuthenticatorClass(IAuthenticator authenticatorClass) {
        if (!initialized) {
            this.authenticatorClass = authenticatorClass;
        }
    }

    public static final class Builder {

        private final DefaultSecurityConfig config = new DefaultSecurityConfig();

        private Builder() {
        }

        public Builder enabled(boolean enabled) {
            config.setEnabled(enabled);
            return this;
        }

        public Builder packageName(String packageName) {
            config.setPackageName(packageName);
            return this;
        }

        public Builder menuFilePath(String menuFilePath) {
            config.setMenuFilePath(menuFilePath);
            return this;
        }

        public Builder authenticatorClass(IAuthenticator authenticatorClass) {
            config.setAuthenticatorClass(authenticatorClass);
            return this;
        }

        public DefaultSecurityConfig build() {
            return config;
        }
    }
}