package com.dpstudio.dev.bug.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.core.persistence.IShardingable;
import net.ymate.platform.core.persistence.annotation.*;
import net.ymate.platform.core.persistence.IConnectionHolder;
import net.ymate.platform.persistence.jdbc.IDatabaseConnectionHolder;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * Bug generated By EntityGenerator on 2020/04/28 上午 08:10:07
 *
 * @author YMP
 * @version 1.0
 */
@Entity(Bug.TABLE_NAME)
public class Bug extends BaseEntity<Bug, String> {

	private static final long serialVersionUID = 1L;

	@Id
	@Property(name = FIELDS.ID, nullable = false, length = 32)
	@Comment("")
    @PropertyState(propertyName = FIELDS.ID)
	private String id;
	
	@Property(name = FIELDS.TITLE, length = 255)
	@Comment("问题标题")
    @PropertyState(propertyName = FIELDS.TITLE)
	private String title;
	
	@Property(name = FIELDS.TYPE, length = 1)
	@Default("0")
	@Comment("类型 0后端 1前端2综合")
    @PropertyState(propertyName = FIELDS.TYPE)
	private Integer type;
	
	@Property(name = FIELDS.LEVEL, length = 1)
	@Default("0")
	@Comment("优先级 0正常 1低 2高 ")
    @PropertyState(propertyName = FIELDS.LEVEL)
	private Integer level;
	
	@Property(name = FIELDS.CONTENT, length = 16383)
	@Comment("问题内容")
    @PropertyState(propertyName = FIELDS.CONTENT)
	private String content;
	
	@Property(name = FIELDS.CREATE_TIME, length = 13)
	@Default("0")
	@Comment("创建时间")
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
	private Long createTime;
	
	@Property(name = FIELDS.STATUS, length = 2)
	@Default("0")
	@Comment("状态 0待处理 1已处理")
    @PropertyState(propertyName = FIELDS.STATUS)
	private Integer status;
	
	@Property(name = FIELDS.HANDLER_USER, length = 32)
	@Comment("处理人")
    @PropertyState(propertyName = FIELDS.HANDLER_USER)
	private String handlerUser;
	
	@Property(name = FIELDS.HANDLER_TIME, length = 13)
	@Default("0")
	@Comment("处理时间")
    @PropertyState(propertyName = FIELDS.HANDLER_TIME)
	private Long handlerTime;
	
	@Property(name = FIELDS.CREATE_USER, length = 32)
	@Comment("提出人")
    @PropertyState(propertyName = FIELDS.CREATE_USER)
	private String createUser;
	
	@Property(name = FIELDS.LAST_MODIFY_USER, length = 32)
	@Comment("最后修改人")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_USER)
	private String lastModifyUser;
	
	@Property(name = FIELDS.LAST_MODIFY_TIME, length = 13)
	@Default("0")
	@Comment("最后修改时间")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_TIME)
	private Long lastModifyTime;

	/**
	 * 构造器
	 */
	public Bug() {
	}

    /**
     * 构造器
     *	@param id
     */
    public Bug(String id) {
        this.id = id;
    }

	/**
	 * 构造器
	 *	@param id
	 *	@param title
	 *	@param type
	 *	@param level
	 *	@param content
	 *	@param createTime
	 *	@param status
	 *	@param handlerUser
	 *	@param handlerTime
	 *	@param createUser
	 *	@param lastModifyUser
	 *	@param lastModifyTime
	 */
	public Bug(String id, String title, Integer type, Integer level, String content, Long createTime, Integer status, String handlerUser, Long handlerTime, String createUser, String lastModifyUser, Long lastModifyTime) {
		this.id = id;
		this.title = title;
		this.type = type;
		this.level = level;
		this.content = content;
		this.createTime = createTime;
		this.status = status;
		this.handlerUser = handlerUser;
		this.handlerTime = handlerTime;
		this.createUser = createUser;
		this.lastModifyUser = lastModifyUser;
		this.lastModifyTime = lastModifyTime;
	}

    @Override
	public String getId() {
		return id;
	}

    @Override
	public void setId(String id) {
		this.id = id;
	}


	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * @return the type
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * @return the level
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * @param level the level to set
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}

	/**
	 * @param content the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * @return the createTime
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the status
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * @return the handlerUser
	 */
	public String getHandlerUser() {
		return handlerUser;
	}

	/**
	 * @param handlerUser the handlerUser to set
	 */
	public void setHandlerUser(String handlerUser) {
		this.handlerUser = handlerUser;
	}

	/**
	 * @return the handlerTime
	 */
	public Long getHandlerTime() {
		return handlerTime;
	}

	/**
	 * @param handlerTime the handlerTime to set
	 */
	public void setHandlerTime(Long handlerTime) {
		this.handlerTime = handlerTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the lastModifyUser
	 */
	public String getLastModifyUser() {
		return lastModifyUser;
	}

	/**
	 * @param lastModifyUser the lastModifyUser to set
	 */
	public void setLastModifyUser(String lastModifyUser) {
		this.lastModifyUser = lastModifyUser;
	}

	/**
	 * @return the lastModifyTime
	 */
	public Long getLastModifyTime() {
		return lastModifyTime;
	}

	/**
	 * @param lastModifyTime the lastModifyTime to set
	 */
	public void setLastModifyTime(Long lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}


	//
	// Chain
	//

	public static BugBuilder builder() {
		return new BugBuilder();
	}

	public BugBuilder bind() {
    	return new BugBuilder(this);
    }

	public static class BugBuilder {

		private Bug _model;

		public BugBuilder() {
			_model = new Bug();
		}

		public BugBuilder(Bug model) {
			_model = model;
		}

		public Bug build() {
			return _model;
		}


		public IDatabaseConnectionHolder connectionHolder() {
			return _model.getConnectionHolder();
		}

		public BugBuilder connectionHolder(IDatabaseConnectionHolder connectionHolder) {
			_model.setConnectionHolder(connectionHolder);
			return this;
		}

		public String dataSourceName() {
			return _model.getDataSourceName();
		}

		public BugBuilder dataSourceName(String dsName) {
			_model.setDataSourceName(dsName);
			return this;
		}

		public IShardingable shardingable() {
			return _model.getShardingable();
		}

		public BugBuilder shardingable(IShardingable shardingable) {
    		_model.setShardingable(shardingable);
    		return this;
    	}

		public String id() {
			return _model.getId();
		}

		public BugBuilder id(String id) {
			_model.setId(id);
			return this;
		}

		public String title() {
			return _model.getTitle();
		}

		public BugBuilder title(String title) {
			_model.setTitle(title);
			return this;
		}

		public Integer type() {
			return _model.getType();
		}

		public BugBuilder type(Integer type) {
			_model.setType(type);
			return this;
		}

		public Integer level() {
			return _model.getLevel();
		}

		public BugBuilder level(Integer level) {
			_model.setLevel(level);
			return this;
		}

		public String content() {
			return _model.getContent();
		}

		public BugBuilder content(String content) {
			_model.setContent(content);
			return this;
		}

		public Long createTime() {
			return _model.getCreateTime();
		}

		public BugBuilder createTime(Long createTime) {
			_model.setCreateTime(createTime);
			return this;
		}

		public Integer status() {
			return _model.getStatus();
		}

		public BugBuilder status(Integer status) {
			_model.setStatus(status);
			return this;
		}

		public String handlerUser() {
			return _model.getHandlerUser();
		}

		public BugBuilder handlerUser(String handlerUser) {
			_model.setHandlerUser(handlerUser);
			return this;
		}

		public Long handlerTime() {
			return _model.getHandlerTime();
		}

		public BugBuilder handlerTime(Long handlerTime) {
			_model.setHandlerTime(handlerTime);
			return this;
		}

		public String createUser() {
			return _model.getCreateUser();
		}

		public BugBuilder createUser(String createUser) {
			_model.setCreateUser(createUser);
			return this;
		}

		public String lastModifyUser() {
			return _model.getLastModifyUser();
		}

		public BugBuilder lastModifyUser(String lastModifyUser) {
			_model.setLastModifyUser(lastModifyUser);
			return this;
		}

		public Long lastModifyTime() {
			return _model.getLastModifyTime();
		}

		public BugBuilder lastModifyTime(Long lastModifyTime) {
			_model.setLastModifyTime(lastModifyTime);
			return this;
		}

	}

	/**
	 * Bug 字段常量表
	 */
	public class FIELDS {
		public static final String ID = "id";
		public static final String TITLE = "title";
		public static final String TYPE = "type";
		public static final String LEVEL = "level";
		public static final String CONTENT = "content";
		public static final String CREATE_TIME = "create_time";
		public static final String STATUS = "status";
		public static final String HANDLER_USER = "handler_user";
		public static final String HANDLER_TIME = "handler_time";
		public static final String CREATE_USER = "create_user";
		public static final String LAST_MODIFY_USER = "last_modify_user";
		public static final String LAST_MODIFY_TIME = "last_modify_time";
	}

	public static final String TABLE_NAME = "bug";

}
