/*
 * Copyright 2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dpstudio.dev.bug.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.core.persistence.annotation.Comment;
import net.ymate.platform.core.persistence.annotation.Default;
import net.ymate.platform.core.persistence.annotation.Entity;
import net.ymate.platform.core.persistence.annotation.Id;
import net.ymate.platform.core.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;
import net.ymate.platform.core.persistence.IShardingable;
import net.ymate.platform.persistence.jdbc.IDatabase;
import net.ymate.platform.persistence.jdbc.IDatabaseConnectionHolder;

/**
 * Bug generated By EntityMojo on 2020/06/30 16:32:30
 *
 * @author YMP (https://www.ymate.net/)
 */
@Entity(Bug.TABLE_NAME)
public class Bug extends BaseEntity<Bug, java.lang.String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = FIELDS.ID, nullable = false, length = 32)
    @Comment("")
    @PropertyState(propertyName = FIELDS.ID)
    private java.lang.String id;


    @Property(name = FIELDS.TITLE, length = 255)
    @Comment("问题标题")
    @PropertyState(propertyName = FIELDS.TITLE)
    private java.lang.String title;


    @Property(name = FIELDS.TYPE, length = 1)
    @Default("0")
    @Comment("类型 0后端 1前端2综合")
    @PropertyState(propertyName = FIELDS.TYPE)
    private java.lang.Integer type;


    @Property(name = FIELDS.LEVEL, length = 1)
    @Default("0")
    @Comment("优先级 0正常 1低 2高 ")
    @PropertyState(propertyName = FIELDS.LEVEL)
    private java.lang.Integer level;


    @Property(name = FIELDS.CONTENT, length = 16383)
    @Comment("问题内容")
    @PropertyState(propertyName = FIELDS.CONTENT)
    private java.lang.String content;


    @Property(name = FIELDS.CREATE_TIME, length = 13)
    @Default("0")
    @Comment("创建时间")
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
    private java.lang.Long createTime;


    @Property(name = FIELDS.STATUS, length = 2)
    @Default("0")
    @Comment("状态 0待处理 1已处理")
    @PropertyState(propertyName = FIELDS.STATUS)
    private java.lang.Integer status;


    @Property(name = FIELDS.HANDLER_USER, length = 32)
    @Comment("处理人")
    @PropertyState(propertyName = FIELDS.HANDLER_USER)
    private java.lang.String handlerUser;


    @Property(name = FIELDS.HANDLER_TIME, length = 13)
    @Default("0")
    @Comment("处理时间")
    @PropertyState(propertyName = FIELDS.HANDLER_TIME)
    private java.lang.Long handlerTime;


    @Property(name = FIELDS.CREATE_USER, length = 32)
    @Comment("提出人")
    @PropertyState(propertyName = FIELDS.CREATE_USER)
    private java.lang.String createUser;


    @Property(name = FIELDS.LAST_MODIFY_USER, length = 32)
    @Comment("最后修改人")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_USER)
    private java.lang.String lastModifyUser;


    @Property(name = FIELDS.LAST_MODIFY_TIME, length = 13)
    @Default("0")
    @Comment("最后修改时间")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_TIME)
    private java.lang.Long lastModifyTime;


    public Bug() {
    }

    public Bug(IDatabase dbOwner) {
        super(dbOwner);
    }

    public Bug(java.lang.String id) {
        this.id = id;
    }

    public Bug(IDatabase dbOwner, java.lang.String id) {
        super(dbOwner);
        this.id = id;
    }

    public Bug(java.lang.String id, java.lang.String title, java.lang.Integer type, java.lang.Integer level, java.lang.String content, java.lang.Long createTime, java.lang.Integer status, java.lang.String handlerUser, java.lang.Long handlerTime, java.lang.String createUser, java.lang.String lastModifyUser, java.lang.Long lastModifyTime) {
        this.id = id;
        this.title = title;
        this.type = type;
        this.level = level;
        this.content = content;
        this.createTime = createTime;
        this.status = status;
        this.handlerUser = handlerUser;
        this.handlerTime = handlerTime;
        this.createUser = createUser;
        this.lastModifyUser = lastModifyUser;
        this.lastModifyTime = lastModifyTime;
    }

    public Bug(IDatabase dbOwner, java.lang.String id, java.lang.String title, java.lang.Integer type, java.lang.Integer level, java.lang.String content, java.lang.Long createTime, java.lang.Integer status, java.lang.String handlerUser, java.lang.Long handlerTime, java.lang.String createUser, java.lang.String lastModifyUser, java.lang.Long lastModifyTime) {
        super(dbOwner);
        this.id = id;
        this.title = title;
        this.type = type;
        this.level = level;
        this.content = content;
        this.createTime = createTime;
        this.status = status;
        this.handlerUser = handlerUser;
        this.handlerTime = handlerTime;
        this.createUser = createUser;
        this.lastModifyUser = lastModifyUser;
        this.lastModifyTime = lastModifyTime;
    }

    @Override
    public java.lang.String getId() {
        return id;
    }

    @Override
    public void setId(java.lang.String id) {
        this.id = id;
    }

    public java.lang.String getTitle() {
        return title;
    }

    public void setTitle(java.lang.String title) {
        this.title = title;
    }

    public java.lang.Integer getType() {
        return type;
    }

    public void setType(java.lang.Integer type) {
        this.type = type;
    }

    public java.lang.Integer getLevel() {
        return level;
    }

    public void setLevel(java.lang.Integer level) {
        this.level = level;
    }

    public java.lang.String getContent() {
        return content;
    }

    public void setContent(java.lang.String content) {
        this.content = content;
    }

    public java.lang.Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.lang.Long createTime) {
        this.createTime = createTime;
    }

    public java.lang.Integer getStatus() {
        return status;
    }

    public void setStatus(java.lang.Integer status) {
        this.status = status;
    }

    public java.lang.String getHandlerUser() {
        return handlerUser;
    }

    public void setHandlerUser(java.lang.String handlerUser) {
        this.handlerUser = handlerUser;
    }

    public java.lang.Long getHandlerTime() {
        return handlerTime;
    }

    public void setHandlerTime(java.lang.Long handlerTime) {
        this.handlerTime = handlerTime;
    }

    public java.lang.String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(java.lang.String createUser) {
        this.createUser = createUser;
    }

    public java.lang.String getLastModifyUser() {
        return lastModifyUser;
    }

    public void setLastModifyUser(java.lang.String lastModifyUser) {
        this.lastModifyUser = lastModifyUser;
    }

    public java.lang.Long getLastModifyTime() {
        return lastModifyTime;
    }

    public void setLastModifyTime(java.lang.Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    public BugBuilder bind() {
        return new BugBuilder(this);
    }

    public static BugBuilder builder() {
        return new BugBuilder();
    }

    public static BugBuilder builder(IDatabase dbOwner) {
        return new BugBuilder(dbOwner);
    }

    public static class BugBuilder {

        private final Bug targetEntity;

        public BugBuilder() {
            targetEntity = new Bug();
        }

        public BugBuilder(IDatabase dbOwner) {
            targetEntity = new Bug(dbOwner);
        }

        public BugBuilder(Bug targetEntity) {
            this.targetEntity = targetEntity;
        }

        public Bug build() {
            return targetEntity;
        }

        public IDatabaseConnectionHolder connectionHolder() {
            return targetEntity.getConnectionHolder();
        }

        public BugBuilder connectionHolder(IDatabaseConnectionHolder connectionHolder) {
            targetEntity.setConnectionHolder(connectionHolder);
            return this;
        }

        public String dataSourceName() {
            return targetEntity.getDataSourceName();
        }

        public BugBuilder dataSourceName(String dataSourceName) {
            targetEntity.setDataSourceName(dataSourceName);
            return this;
        }

        public IShardingable shardingable() {
            return targetEntity.getShardingable();
        }

        public BugBuilder shardingable(IShardingable shardingable) {
            targetEntity.setShardingable(shardingable);
            return this;
        }


        public java.lang.String id() {
            return targetEntity.getId();
        }

        public BugBuilder id(java.lang.String id) {
            targetEntity.setId(id);
            return this;
        }

        public java.lang.String title() {
            return targetEntity.getTitle();
        }

        public BugBuilder title(java.lang.String title) {
            targetEntity.setTitle(title);
            return this;
        }

        public java.lang.Integer type() {
            return targetEntity.getType();
        }

        public BugBuilder type(java.lang.Integer type) {
            targetEntity.setType(type);
            return this;
        }

        public java.lang.Integer level() {
            return targetEntity.getLevel();
        }

        public BugBuilder level(java.lang.Integer level) {
            targetEntity.setLevel(level);
            return this;
        }

        public java.lang.String content() {
            return targetEntity.getContent();
        }

        public BugBuilder content(java.lang.String content) {
            targetEntity.setContent(content);
            return this;
        }

        public java.lang.Long createTime() {
            return targetEntity.getCreateTime();
        }

        public BugBuilder createTime(java.lang.Long createTime) {
            targetEntity.setCreateTime(createTime);
            return this;
        }

        public java.lang.Integer status() {
            return targetEntity.getStatus();
        }

        public BugBuilder status(java.lang.Integer status) {
            targetEntity.setStatus(status);
            return this;
        }

        public java.lang.String handlerUser() {
            return targetEntity.getHandlerUser();
        }

        public BugBuilder handlerUser(java.lang.String handlerUser) {
            targetEntity.setHandlerUser(handlerUser);
            return this;
        }

        public java.lang.Long handlerTime() {
            return targetEntity.getHandlerTime();
        }

        public BugBuilder handlerTime(java.lang.Long handlerTime) {
            targetEntity.setHandlerTime(handlerTime);
            return this;
        }

        public java.lang.String createUser() {
            return targetEntity.getCreateUser();
        }

        public BugBuilder createUser(java.lang.String createUser) {
            targetEntity.setCreateUser(createUser);
            return this;
        }

        public java.lang.String lastModifyUser() {
            return targetEntity.getLastModifyUser();
        }

        public BugBuilder lastModifyUser(java.lang.String lastModifyUser) {
            targetEntity.setLastModifyUser(lastModifyUser);
            return this;
        }

        public java.lang.Long lastModifyTime() {
            return targetEntity.getLastModifyTime();
        }

        public BugBuilder lastModifyTime(java.lang.Long lastModifyTime) {
            targetEntity.setLastModifyTime(lastModifyTime);
            return this;
        }
    }

    public interface FIELDS {
        String ID = "id";
        String TITLE = "title";
        String TYPE = "type";
        String LEVEL = "level";
        String CONTENT = "content";
        String CREATE_TIME = "create_time";
        String STATUS = "status";
        String HANDLER_USER = "handler_user";
        String HANDLER_TIME = "handler_time";
        String CREATE_USER = "create_user";
        String LAST_MODIFY_USER = "last_modify_user";
        String LAST_MODIFY_TIME = "last_modify_time";
    }

    public static final String TABLE_NAME = "bug";
}
