package com.dpstudio.dev.bug.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.IShardingable;
import net.ymate.platform.persistence.annotation.*;
import net.ymate.platform.persistence.jdbc.IConnectionHolder;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * BugLog generated By EntityGenerator on 2020/04/28 上午 09:03:51
 *
 * @author YMP
 * @version 1.0
 */
@Entity(BugLog.TABLE_NAME)
public class BugLog extends BaseEntity<BugLog, String> {

	private static final long serialVersionUID = 1L;

	@Id
	@Property(name = FIELDS.ID, nullable = false, length = 32)
	@Comment("")
    @PropertyState(propertyName = FIELDS.ID)
	private String id;
	
	@Property(name = FIELDS.BUG_ID, nullable = false, length = 32)
	@Comment("")
    @PropertyState(propertyName = FIELDS.BUG_ID)
	private String bugId;
	
	@Property(name = FIELDS.HANDLER_USER, nullable = false, length = 100)
	@Comment("处理人")
    @PropertyState(propertyName = FIELDS.HANDLER_USER)
	private String handlerUser;
	
	@Property(name = FIELDS.HANDLER_TIME, length = 13)
	@Default("0")
	@Comment("处理时间")
    @PropertyState(propertyName = FIELDS.HANDLER_TIME)
	private Long handlerTime;
	
	@Property(name = FIELDS.ACTION, length = 32)
	@Comment("动作")
    @PropertyState(propertyName = FIELDS.ACTION)
	private String action;

	/**
	 * 构造器
	 */
	public BugLog() {
	}

    /**
     * 构造器
     *	@param id
     *	@param bugId
     *	@param handlerUser
     */
    public BugLog(String id, String bugId, String handlerUser) {
        this.id = id;
        this.bugId = bugId;
        this.handlerUser = handlerUser;
    }

	/**
	 * 构造器
	 *	@param id
	 *	@param bugId
	 *	@param handlerUser
	 *	@param handlerTime
	 *	@param action
	 */
	public BugLog(String id, String bugId, String handlerUser, Long handlerTime, String action) {
		this.id = id;
		this.bugId = bugId;
		this.handlerUser = handlerUser;
		this.handlerTime = handlerTime;
		this.action = action;
	}

    @Override
	public String getId() {
		return id;
	}

    @Override
	public void setId(String id) {
		this.id = id;
	}


	/**
	 * @return the bugId
	 */
	public String getBugId() {
		return bugId;
	}

	/**
	 * @param bugId the bugId to set
	 */
	public void setBugId(String bugId) {
		this.bugId = bugId;
	}

	/**
	 * @return the handlerUser
	 */
	public String getHandlerUser() {
		return handlerUser;
	}

	/**
	 * @param handlerUser the handlerUser to set
	 */
	public void setHandlerUser(String handlerUser) {
		this.handlerUser = handlerUser;
	}

	/**
	 * @return the handlerTime
	 */
	public Long getHandlerTime() {
		return handlerTime;
	}

	/**
	 * @param handlerTime the handlerTime to set
	 */
	public void setHandlerTime(Long handlerTime) {
		this.handlerTime = handlerTime;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}


	//
	// Chain
	//

	public static BugLogBuilder builder() {
		return new BugLogBuilder();
	}

	public BugLogBuilder bind() {
    	return new BugLogBuilder(this);
    }

	public static class BugLogBuilder {

		private BugLog _model;

		public BugLogBuilder() {
			_model = new BugLog();
		}

		public BugLogBuilder(BugLog model) {
			_model = model;
		}

		public BugLog build() {
			return _model;
		}


		public IConnectionHolder connectionHolder() {
			return _model.getConnectionHolder();
		}

		public BugLogBuilder connectionHolder(IConnectionHolder connectionHolder) {
			_model.setConnectionHolder(connectionHolder);
			return this;
		}

		public String dataSourceName() {
			return _model.getDataSourceName();
		}

		public BugLogBuilder dataSourceName(String dsName) {
			_model.setDataSourceName(dsName);
			return this;
		}

		public IShardingable shardingable() {
			return _model.getShardingable();
		}

		public BugLogBuilder shardingable(IShardingable shardingable) {
    		_model.setShardingable(shardingable);
    		return this;
    	}

		public String id() {
			return _model.getId();
		}

		public BugLogBuilder id(String id) {
			_model.setId(id);
			return this;
		}

		public String bugId() {
			return _model.getBugId();
		}

		public BugLogBuilder bugId(String bugId) {
			_model.setBugId(bugId);
			return this;
		}

		public String handlerUser() {
			return _model.getHandlerUser();
		}

		public BugLogBuilder handlerUser(String handlerUser) {
			_model.setHandlerUser(handlerUser);
			return this;
		}

		public Long handlerTime() {
			return _model.getHandlerTime();
		}

		public BugLogBuilder handlerTime(Long handlerTime) {
			_model.setHandlerTime(handlerTime);
			return this;
		}

		public String action() {
			return _model.getAction();
		}

		public BugLogBuilder action(String action) {
			_model.setAction(action);
			return this;
		}

	}

	/**
	 * BugLog 字段常量表
	 */
	public class FIELDS {
		public static final String ID = "id";
		public static final String BUG_ID = "bug_id";
		public static final String HANDLER_USER = "handler_user";
		public static final String HANDLER_TIME = "handler_time";
		public static final String ACTION = "action";
	}

	public static final String TABLE_NAME = "bug_log";

}
