package com.dpstudio.dev.bug.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.core.persistence.IShardingable;
import net.ymate.platform.core.persistence.annotation.*;
import net.ymate.platform.core.persistence.IConnectionHolder;
import net.ymate.platform.persistence.jdbc.IDatabaseConnectionHolder;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * BugUser generated By EntityGenerator on 2020/04/28 上午 08:10:07
 *
 * @author YMP
 * @version 1.0
 */
@Entity(BugUser.TABLE_NAME)
public class BugUser extends BaseEntity<BugUser, String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = FIELDS.ID, nullable = false, length = 32)
    @Comment("")
    @PropertyState(propertyName = FIELDS.ID)
    private String id;

    @Property(name = FIELDS.NAME, nullable = false, length = 100)
    @Comment("名称")
    @PropertyState(propertyName = FIELDS.NAME)
    private String name;

    @Property(name = FIELDS.CREATE_TIME, length = 13)
    @Default("0")
    @Comment("创建时间")
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
    private Long createTime;

    /**
     * 构造器
     */
    public BugUser() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param name
     */
    public BugUser(String id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * 构造器
     *
     * @param id
     * @param name
     * @param createTime
     */
    public BugUser(String id, String name, Long createTime) {
        this.id = id;
        this.name = name;
        this.createTime = createTime;
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }


    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the createTime
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the createTime to set
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }


    //
    // Chain
    //

    public static BugUserBuilder builder() {
        return new BugUserBuilder();
    }

    public BugUserBuilder bind() {
        return new BugUserBuilder(this);
    }

    public static class BugUserBuilder {

        private BugUser _model;

        public BugUserBuilder() {
            _model = new BugUser();
        }

        public BugUserBuilder(BugUser model) {
            _model = model;
        }

        public BugUser build() {
            return _model;
        }


        public IDatabaseConnectionHolder connectionHolder() {
            return _model.getConnectionHolder();
        }

        public BugUserBuilder connectionHolder(IDatabaseConnectionHolder connectionHolder) {
            _model.setConnectionHolder(connectionHolder);
            return this;
        }

        public String dataSourceName() {
            return _model.getDataSourceName();
        }

        public BugUserBuilder dataSourceName(String dsName) {
            _model.setDataSourceName(dsName);
            return this;
        }

        public IShardingable shardingable() {
            return _model.getShardingable();
        }

        public BugUserBuilder shardingable(IShardingable shardingable) {
            _model.setShardingable(shardingable);
            return this;
        }

        public String id() {
            return _model.getId();
        }

        public BugUserBuilder id(String id) {
            _model.setId(id);
            return this;
        }

        public String name() {
            return _model.getName();
        }

        public BugUserBuilder name(String name) {
            _model.setName(name);
            return this;
        }

        public Long createTime() {
            return _model.getCreateTime();
        }

        public BugUserBuilder createTime(Long createTime) {
            _model.setCreateTime(createTime);
            return this;
        }

    }

    /**
     * BugUser 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String NAME = "name";
        public static final String CREATE_TIME = "create_time";
    }

    public static final String TABLE_NAME = "bug_user";

}
