package ${daoPackageName};

import ${modelPackageName}.${modelName?cap_first};
import net.ymate.platform.persistence.IResultSet;
import java.util.List;

/**
* @Author: CurdGenerateImpl.
* @Date: ${lastUpdateTime?string("yyyy/MM/dd")}.
* @Time: ${lastUpdateTime?string("HH:mm:ss")}.
* @Description: I${modelName?cap_first}Dao generated By CurdGenerateImpl on ${lastUpdateTime?string("yyyy/MM/dd a HH:mm:ss")}
*/
public interface I${modelName?cap_first}Dao {

    /**
    * 添加
    *
    * @param ${modelName?uncap_first} 添加的数据信息
    * @return 添加成功的数据信息
    * @throws Exception 添加异常
    */
    ${modelName?cap_first} create(${modelName?cap_first} ${modelName?uncap_first}) throws Exception;

    /**
    * 修改
    *
    * @param ${modelName?uncap_first} 修改的数据信息
    * @param fields                   要修改哪些字段
    * @return 修改成功的数据信息
    * @throws Exception 修改异常
    */
    ${modelName?cap_first} update(${modelName?cap_first} ${modelName?uncap_first}, String... fields) throws Exception;

    /**
    * 删除
    *
    * @param ${modelName?uncap_first}List 要删除的集合
    * @throws Exception 删除异常
    */
    void delete(List<${modelName?cap_first}> ${modelName?uncap_first}List) throws Exception;

    /**
    * 根据id查询
    *
    * @param id     数据id
    * @param fields 要查询哪些字段
    * @return 查询的数据
    * @throws Exception 查询异常
    */
    ${modelName?cap_first} findById(String id,String... fields) throws Exception;

    /**
    * 查询所有
    *
    <#list fieldList as field>
    * @param ${field.varName} ${field.remarks}
    </#list>
    * @param page     第几页
    * @param pageSize 每页显示多少条
    * @return 查询的数据
    * @throws Exception 查询异常
    */
    IResultSet<${modelName?cap_first}> findAll(<#list fieldList as field>${field.varType} ${field.varName}<#if field_has_next>, </#if></#list>, int page, int pageSize) throws Exception;

}
