package ${servicePackageName};

import com.dpstudio.dev.core.R;
import ${modelPackageName}.${modelName?cap_first};
import net.ymate.platform.persistence.IResultSet;
import java.util.List;

/**
* @Author: CurdGenerateImpl.
* @Date: ${lastUpdateTime?string("yyyy/MM/dd")}.
* @Time: ${lastUpdateTime?string("HH:mm:ss")}.
* @Description: I${modelName?cap_first}Service generated By CurdGenerateImpl on ${lastUpdateTime?string("yyyy/MM/dd a HH:mm:ss")}
*/
public interface I${modelName?cap_first}Service {

    /**
    * 添加
    *
    <#list fieldList as field>
        <#if (field.varName!"id") != 'id'>
    * @param ${field.varName} ${field.remarks}
        </#if>
    </#list>
    * @return 添加成功的数据信息
    * @throws Exception 添加异常
    */
    R create(<#list fieldList as field><#if (field.varName!"id") != 'id'>${field.varType} ${field.varName}<#if field_has_next>, </#if></#if></#list>) throws Exception;

    /**
    * 修改
    *
    <#list fieldList as field>
    * @param ${field.varName} ${field.remarks}
    </#list>
    * @return 修改成功的数据信息
    * @throws Exception 修改异常
    */
    R update(<#list fieldList as field>${field.varType} ${field.varName}<#if field_has_next>, </#if></#list>) throws Exception;

    /**
    * 删除
    *
    * @param ids 要删除的id数组
    * @throws Exception 删除异常
    */
    R delete(String[] ids) throws Exception;

    /**
    * 根据id查询
    *
    * @param id     数据id
    * @param fields 要查询哪些字段
    * @return 查询的数据
    * @throws Exception 查询异常
    */
    ${modelName?cap_first} findById(String id,String... fields) throws Exception;

    /**
    * 查询所有
    *
    <#list fieldList as field>
    * @param ${field.varName} ${field.remarks}
    </#list>
    * @param page     第几页
    * @param pageSize 每页显示多少条
    * @return 查询的数据
    * @throws Exception 查询异常
    */
    IResultSet<${modelName?cap_first}> findAll(<#list fieldList as field>${field.varType} ${field.varName}<#if field_has_next>, </#if></#list>, int page, int pageSize) throws Exception;

}