package ${packageName};

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.Comment;
import net.ymate.platform.persistence.annotation.Default;
import net.ymate.platform.persistence.annotation.Entity;
import net.ymate.platform.persistence.annotation.Id;
import net.ymate.platform.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;
import net.ymate.platform.persistence.IShardingable;
import net.ymate.platform.persistence.jdbc.IConnectionHolder;
import org.apache.commons.lang.StringUtils;
import java.util.Scanner;
import java.io.Serializable;

/**
* @Author: ModelGenerateImpl.
* @Date: ${lastUpdateTime?string("yyyy/MM/dd")}.
* @Time: ${lastUpdateTime?string("HH:mm:ss")}.
* @Description: ${voName?cap_first} generated By VoGenerateImpl on ${lastUpdateTime?string("yyyy/MM/dd a HH:mm:ss")}
*/
public class ${voName?cap_first} implements Serializable {

<#list fieldList as field>
    private ${field.varType} ${field.varName};
</#list>

    /**
    * 构造器
<#list fieldList as field>
    *@param ${field.varName}
</#list>
    */
    public ${voName?cap_first}(<#list fieldList as field>${field.varType} ${field.varName}<#if field_has_next>, </#if></#list>) {
<#list fieldList as field>
        this.${field.varName} = ${field.varName};
</#list>
    }

<#list fieldList as field>
    /**
    * @return the ${field.varName}
    */
    public ${field.varType} get${field.varName?cap_first}() {
        return ${field.varName};
    }

    /**
    * @param ${field.varName} the ${field.varName} to set
    */
    public void set${field.varName?cap_first}(${field.varType} ${field.varName}) {
        this.${field.varName} = ${field.varName};
    }
</#list>

<#list fieldList as field>

    /**
    * @return the ${field.varName}
    */
    public ${field.varType} ${field.varName?uncap_first}() {
        return this.get${field.varName?cap_first};
    }
    /**
    * @param ${field.varName} the ${field.varName} to set
    */
    public ${voName?cap_first} set${field.varName?cap_first}(${field.varType} ${field.varName}) {
        this.${field.varName} = ${field.varName};
        return this;
    }
</#list>

}
