/*
 * Copyright 2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dpstudio.dev.log.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.core.persistence.annotation.Comment;
import net.ymate.platform.core.persistence.annotation.Default;
import net.ymate.platform.core.persistence.annotation.Entity;
import net.ymate.platform.core.persistence.annotation.Id;
import net.ymate.platform.core.persistence.annotation.Property;
import net.ymate.platform.core.persistence.annotation.Readonly;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;
import net.ymate.platform.core.persistence.IShardingable;
import net.ymate.platform.persistence.jdbc.IDatabase;
import net.ymate.platform.persistence.jdbc.IDatabaseConnectionHolder;

/**
 * Log generated By EntityMojo on 2020/11/06 14:01:55
 *
 * @author YMP (https://www.ymate.net/)
 */
@Entity(Log.TABLE_NAME)
public class Log extends BaseEntity<Log, java.lang.String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = FIELDS.ID, nullable = false, length = 32)
    @Comment("id")
    @PropertyState(propertyName = FIELDS.ID)
    private java.lang.String id;

    
    @Property(name = FIELDS.MODULE_TYPE, nullable = false, length = 2)
    @Comment("模块类型具体看配置")
    @PropertyState(propertyName = FIELDS.MODULE_TYPE)
    private java.lang.Integer moduleType;

    
    @Property(name = FIELDS.MODULE_NAME, nullable = false, length = 100)
    @Comment("模块名称具体看配置")
    @PropertyState(propertyName = FIELDS.MODULE_NAME)
    private java.lang.String moduleName;

    
    @Property(name = FIELDS.TYPE, nullable = false, length = 2)
    @Comment("日志类型具体看配置")
    @PropertyState(propertyName = FIELDS.TYPE)
    private java.lang.Integer type;

    
    @Property(name = FIELDS.ACTION, nullable = false, length = 100)
    @Comment("日志类型字符串")
    @PropertyState(propertyName = FIELDS.ACTION)
    private java.lang.String action;

    
    @Property(name = FIELDS.RESOURCE_ID, nullable = false, length = 32)
    @Comment("日志对象id")
    @PropertyState(propertyName = FIELDS.RESOURCE_ID)
    private java.lang.String resourceId;

    
    @Property(name = FIELDS.CONTENT, nullable = false, length = 16383)
    @Comment("内容")
    @PropertyState(propertyName = FIELDS.CONTENT)
    private java.lang.String content;

    
    @Property(name = FIELDS.CREATE_USER, nullable = false, length = 32)
    @Comment("创建人")
    @PropertyState(propertyName = FIELDS.CREATE_USER)
    private java.lang.String createUser;

    
    @Property(name = FIELDS.CREATE_TIME, nullable = false, length = 13)
    @Default("0")
    @Comment("创建时间")
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
    private java.lang.Long createTime;


    public Log() {
    }

    public Log(IDatabase dbOwner) {
        super(dbOwner);
    }


    public Log(java.lang.String id, java.lang.Integer moduleType, java.lang.String moduleName, java.lang.Integer type, java.lang.String action, java.lang.String resourceId, java.lang.String content, java.lang.String createUser, java.lang.Long createTime) {
        this.id = id;
        this.moduleType = moduleType;
        this.moduleName = moduleName;
        this.type = type;
        this.action = action;
        this.resourceId = resourceId;
        this.content = content;
        this.createUser = createUser;
        this.createTime = createTime;
    }

    public Log(IDatabase dbOwner, java.lang.String id, java.lang.Integer moduleType, java.lang.String moduleName, java.lang.Integer type, java.lang.String action, java.lang.String resourceId, java.lang.String content, java.lang.String createUser, java.lang.Long createTime) {
        super(dbOwner);
        this.id = id;
        this.moduleType = moduleType;
        this.moduleName = moduleName;
        this.type = type;
        this.action = action;
        this.resourceId = resourceId;
        this.content = content;
        this.createUser = createUser;
        this.createTime = createTime;
    }

    @Override
    public java.lang.String getId() {
        return id;
    }

    @Override
    public void setId(java.lang.String id) {
        this.id = id;
    }

    public java.lang.Integer getModuleType() {
        return moduleType;
    }

    public void setModuleType(java.lang.Integer moduleType) {
        this.moduleType = moduleType;
    }

    public java.lang.String getModuleName() {
        return moduleName;
    }

    public void setModuleName(java.lang.String moduleName) {
        this.moduleName = moduleName;
    }

    public java.lang.Integer getType() {
        return type;
    }

    public void setType(java.lang.Integer type) {
        this.type = type;
    }

    public java.lang.String getAction() {
        return action;
    }

    public void setAction(java.lang.String action) {
        this.action = action;
    }

    public java.lang.String getResourceId() {
        return resourceId;
    }

    public void setResourceId(java.lang.String resourceId) {
        this.resourceId = resourceId;
    }

    public java.lang.String getContent() {
        return content;
    }

    public void setContent(java.lang.String content) {
        this.content = content;
    }

    public java.lang.String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(java.lang.String createUser) {
        this.createUser = createUser;
    }

    public java.lang.Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.lang.Long createTime) {
        this.createTime = createTime;
    }


    public Builder bind() {
        return new Builder(this);
    }

    public static Builder builder() {
        return new Builder();
    }

        public static Builder builder(IDatabase dbOwner) {
            return new Builder(dbOwner);
        }

    public static class Builder {

        private final Log targetEntity;

        public Builder() {
            targetEntity = new Log();
        }

        public Builder(IDatabase dbOwner) {
            targetEntity = new Log(dbOwner);
        }

        public Builder(Log targetEntity) {
            this.targetEntity = targetEntity;
        }

        public Log build() {
            return targetEntity;
        }

        public IDatabaseConnectionHolder connectionHolder() {
            return targetEntity.getConnectionHolder();
        }

        public Builder connectionHolder(IDatabaseConnectionHolder connectionHolder) {
            targetEntity.setConnectionHolder(connectionHolder);
            return this;
        }

        public String dataSourceName() {
            return targetEntity.getDataSourceName();
        }

        public Builder dataSourceName(String dataSourceName) {
            targetEntity.setDataSourceName(dataSourceName);
            return this;
        }

        public IShardingable shardingable() {
            return targetEntity.getShardingable();
        }

        public Builder shardingable(IShardingable shardingable) {
            targetEntity.setShardingable(shardingable);
            return this;
        }


        public java.lang.String id() {
            return targetEntity.getId();
        }

        public Builder id(java.lang.String id) {
            targetEntity.setId(id);
            return this;
        }

        public java.lang.Integer moduleType() {
            return targetEntity.getModuleType();
        }

        public Builder moduleType(java.lang.Integer moduleType) {
            targetEntity.setModuleType(moduleType);
            return this;
        }

        public java.lang.String moduleName() {
            return targetEntity.getModuleName();
        }

        public Builder moduleName(java.lang.String moduleName) {
            targetEntity.setModuleName(moduleName);
            return this;
        }

        public java.lang.Integer type() {
            return targetEntity.getType();
        }

        public Builder type(java.lang.Integer type) {
            targetEntity.setType(type);
            return this;
        }

        public java.lang.String action() {
            return targetEntity.getAction();
        }

        public Builder action(java.lang.String action) {
            targetEntity.setAction(action);
            return this;
        }

        public java.lang.String resourceId() {
            return targetEntity.getResourceId();
        }

        public Builder resourceId(java.lang.String resourceId) {
            targetEntity.setResourceId(resourceId);
            return this;
        }

        public java.lang.String content() {
            return targetEntity.getContent();
        }

        public Builder content(java.lang.String content) {
            targetEntity.setContent(content);
            return this;
        }

        public java.lang.String createUser() {
            return targetEntity.getCreateUser();
        }

        public Builder createUser(java.lang.String createUser) {
            targetEntity.setCreateUser(createUser);
            return this;
        }

        public java.lang.Long createTime() {
            return targetEntity.getCreateTime();
        }

        public Builder createTime(java.lang.Long createTime) {
            targetEntity.setCreateTime(createTime);
            return this;
        }
    }

    public interface FIELDS {
        String ID = "id";
        String MODULE_TYPE = "module_type";
        String MODULE_NAME = "module_name";
        String TYPE = "type";
        String ACTION = "action";
        String RESOURCE_ID = "resource_id";
        String CONTENT = "content";
        String CREATE_USER = "create_user";
        String CREATE_TIME = "create_time";
    }

    public static final String TABLE_NAME = "log";
}
