package com.dpstudio.dev.log.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.IShardingable;
import net.ymate.platform.persistence.annotation.*;
import net.ymate.platform.persistence.jdbc.IConnectionHolder;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * Log generated By EntityGenerator on 2020/05/26 上午 09:31:09
 *
 * @author YMP
 * @version 1.0
 */
@Entity(Log.TABLE_NAME)
public class Log extends BaseEntity<Log, String> {

	private static final long serialVersionUID = 1L;

	@Id
	@Property(name = FIELDS.ID, nullable = false, length = 32)
	@Comment("")
    @PropertyState(propertyName = FIELDS.ID)
	private String id;
	
	@Property(name = FIELDS.MODULE_TYPE, nullable = false, length = 4)
	@Default("0")
	@Comment("模块类型")
    @PropertyState(propertyName = FIELDS.MODULE_TYPE)
	private Integer moduleType;
	
	@Property(name = FIELDS.MODULE_NAME, nullable = false, length = 32)
	@Comment("模块名称")
    @PropertyState(propertyName = FIELDS.MODULE_NAME)
	private String moduleName;
	
	@Property(name = FIELDS.TYPE, nullable = false, length = 4)
	@Default("0")
	@Comment("日志类型")
    @PropertyState(propertyName = FIELDS.TYPE)
	private Integer type;
	
	@Property(name = FIELDS.ACTION, nullable = false, length = 32)
	@Comment("日志类型字符串")
    @PropertyState(propertyName = FIELDS.ACTION)
	private String action;
	
	@Property(name = FIELDS.RESOURCE_ID, nullable = false, length = 32)
	@Comment("日志对象id")
    @PropertyState(propertyName = FIELDS.RESOURCE_ID)
	private String resourceId;
	
	@Property(name = FIELDS.CREATE_USER, nullable = false, length = 32)
	@Comment("创建人")
    @PropertyState(propertyName = FIELDS.CREATE_USER)
	private String createUser;
	
	@Property(name = FIELDS.CREATE_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("创建时间")
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
	private Long createTime;
	
	@Property(name = FIELDS.CONTENT, nullable = false, length = 16383)
	@Comment("内容")
    @PropertyState(propertyName = FIELDS.CONTENT)
	private String content;

	/**
	 * 构造器
	 */
	public Log() {
	}


	/**
	 * 构造器
	 *	@param id
	 *	@param moduleType
	 *	@param moduleName
	 *	@param type
	 *	@param action
	 *	@param resourceId
	 *	@param createUser
	 *	@param createTime
	 *	@param content
	 */
	public Log(String id, Integer moduleType, String moduleName, Integer type, String action, String resourceId, String createUser, Long createTime, String content) {
		this.id = id;
		this.moduleType = moduleType;
		this.moduleName = moduleName;
		this.type = type;
		this.action = action;
		this.resourceId = resourceId;
		this.createUser = createUser;
		this.createTime = createTime;
		this.content = content;
	}

    @Override
	public String getId() {
		return id;
	}

    @Override
	public void setId(String id) {
		this.id = id;
	}


	/**
	 * @return the moduleType
	 */
	public Integer getModuleType() {
		return moduleType;
	}

	/**
	 * @param moduleType the moduleType to set
	 */
	public void setModuleType(Integer moduleType) {
		this.moduleType = moduleType;
	}

	/**
	 * @return the moduleName
	 */
	public String getModuleName() {
		return moduleName;
	}

	/**
	 * @param moduleName the moduleName to set
	 */
	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	/**
	 * @return the type
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the resourceId
	 */
	public String getResourceId() {
		return resourceId;
	}

	/**
	 * @param resourceId the resourceId to set
	 */
	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createTime
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}

	/**
	 * @param content the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}


	//
	// Chain
	//

	public static LogBuilder builder() {
		return new LogBuilder();
	}

	public LogBuilder bind() {
    	return new LogBuilder(this);
    }

	public static class LogBuilder {

		private Log _model;

		public LogBuilder() {
			_model = new Log();
		}

		public LogBuilder(Log model) {
			_model = model;
		}

		public Log build() {
			return _model;
		}


		public IConnectionHolder connectionHolder() {
			return _model.getConnectionHolder();
		}

		public LogBuilder connectionHolder(IConnectionHolder connectionHolder) {
			_model.setConnectionHolder(connectionHolder);
			return this;
		}

		public String dataSourceName() {
			return _model.getDataSourceName();
		}

		public LogBuilder dataSourceName(String dsName) {
			_model.setDataSourceName(dsName);
			return this;
		}

		public IShardingable shardingable() {
			return _model.getShardingable();
		}

		public LogBuilder shardingable(IShardingable shardingable) {
    		_model.setShardingable(shardingable);
    		return this;
    	}

		public String id() {
			return _model.getId();
		}

		public LogBuilder id(String id) {
			_model.setId(id);
			return this;
		}

		public Integer moduleType() {
			return _model.getModuleType();
		}

		public LogBuilder moduleType(Integer moduleType) {
			_model.setModuleType(moduleType);
			return this;
		}

		public String moduleName() {
			return _model.getModuleName();
		}

		public LogBuilder moduleName(String moduleName) {
			_model.setModuleName(moduleName);
			return this;
		}

		public Integer type() {
			return _model.getType();
		}

		public LogBuilder type(Integer type) {
			_model.setType(type);
			return this;
		}

		public String action() {
			return _model.getAction();
		}

		public LogBuilder action(String action) {
			_model.setAction(action);
			return this;
		}

		public String resourceId() {
			return _model.getResourceId();
		}

		public LogBuilder resourceId(String resourceId) {
			_model.setResourceId(resourceId);
			return this;
		}

		public String createUser() {
			return _model.getCreateUser();
		}

		public LogBuilder createUser(String createUser) {
			_model.setCreateUser(createUser);
			return this;
		}

		public Long createTime() {
			return _model.getCreateTime();
		}

		public LogBuilder createTime(Long createTime) {
			_model.setCreateTime(createTime);
			return this;
		}

		public String content() {
			return _model.getContent();
		}

		public LogBuilder content(String content) {
			_model.setContent(content);
			return this;
		}

	}

	/**
	 * Log 字段常量表
	 */
	public class FIELDS {
		public static final String ID = "id";
		public static final String MODULE_TYPE = "module_type";
		public static final String MODULE_NAME = "module_name";
		public static final String TYPE = "type";
		public static final String ACTION = "action";
		public static final String RESOURCE_ID = "resource_id";
		public static final String CREATE_USER = "create_user";
		public static final String CREATE_TIME = "create_time";
		public static final String CONTENT = "content";
	}

	public static final String TABLE_NAME = "log";

}
