/*
 * Copyright 2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dpstudio.dev.doc;

import net.ymate.platform.core.beans.annotation.Ignored;
import net.ymate.platform.core.support.IInitialization;

/**
 * IDocConfig generated By ModuleMojo on 2020/07/07 15:44
 *
 * @author YMP (https://www.ymate.net/)
 */
@Ignored
public interface IDocConfig extends IInitialization<IDoc> {

    String ENABLED = "enabled";
    String MOCK_ENABLED = "mock_enabled";
    String SDK_ENABLED = "sdk_enabled";
    String TITLE = "title";
    String SOURCE_PATH = "source_path";
    String FILE_NAME = "file_name";
    String VERSION = "version";
    String HOST = "host";

    /**
     * 模块是否已启用, 默认值: true
     *
     * @return 返回false表示禁用
     */
    boolean isEnabled();

    /**
     * mock是否可用, 默认值: true
     *
     * @return 返回false表示禁用
     */
    boolean isMockEnabled();

    /**
     * sdk是否可用, 默认值: true
     *
     * @return 返回false表示禁用
     */
    boolean isSdkEnabled();

    /**
     * 文档标题
     *
     * @return 文档标题
     */
    String title();

    /**
     * 代码源码路径用逗号(, )分割
     *
     * @return 代码源码路径用逗号(, )分割
     */
    String sourcePath();

    /**
     * java文件包含名称 用逗号(,)分割
     *
     * @return java文件包含名称 用逗号(,)分割
     */
    String fileName();

    /**
     * 文档版本
     *
     * @return 文档版本
     */
    String version();

    /**
     * 接口路径
     *
     * @return 接口路径
     */
    String host();
}